### ISSUE TITLE
SHA1 no longer allowed in some environments

### ISSUE THREAD

**Issue by icf-mrankin** [marcins/cf-google-authenticator#6]
Because of the crack of SHA1, NIST is now preventing its use on federal websites.  I took a quick run at it but was unable to get it to work correctly.  Maybe someone can figure out how to get this to work with SHA256 or SHA512?

**Comment by akelly777** [comment]
I had ChatGPT take a pass at it. Any interest in the result?

**Comment by icf-mrankin** [comment]
Stale.
